source 'https://rubygems.org'


gem 'rails', '~> 5.0.0'
gem 'mysql2', '~> 0.4.4'
gem 'puma', '~> 3.0'
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem "pundit"
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

#Authentication
 gem 'jwt', '~> 1.5', '>= 1.5.4'
 gem 'devise', '~> 4.2'

 gem 'paperclip', '~> 4.3', '>= 4.3.6'
 gem 'dotenv-rails'
 gem 'sidekiq'
 gem 'devise-async'
 gem 'aasm'

#Pagination
gem 'will_paginate', '~> 3.1.0'

group :development, :test, :gitlabci do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 9.0.5'
  gem 'pry-byebug', '~> 3.4'
  gem 'rspec', '~> 3.5'
  gem 'rspec-rails', '3.5.1'
  gem 'factory_girl_rails', '~> 4.7'
  gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
  gem 'rails-controller-testing'
  gem 'pundit-matchers'
  gem 'timecop', '~> 0.8.1'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring', '~> 1.7'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
